const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');

// We could require Survey model from the model file,
// but sometimes mongoose complains during testing ('too many requests').
const Survey = mongoose.model('surveys');

module.exports = app => {
    app.post('/api/surveys', requireLogin, requireCredits, (req, res) => {
        const { title, subject, body, recipients } = req.body;

        const survey = new Survey({
            title,
            subject,
            body,
            recipients: recipients.split(',').map( email => ({ email: email.trim() }) ),
            // id generated by Mongo (mongoose)
            _user: req.user.id,
            dateSent: Date.now()
        });

        // Send an email here
        const mailer = new Mailer(survey, surveyTemplate(survey));
        mailer.send();

    });
};